************* Module reinforce.experiments.experiment_runner
reinforce/experiments/experiment_runner.py:174:15: W0718: Catching too general exception Exception (broad-exception-caught)
************* Module reinforce.experiments.hyperparameter_search
reinforce/experiments/hyperparameter_search.py:113:0: C0301: Line too long (120/119) (line-too-long)
reinforce/experiments/hyperparameter_search.py:195:15: W0718: Catching too general exception Exception (broad-exception-caught)
reinforce/experiments/hyperparameter_search.py:526:19: W0718: Catching too general exception Exception (broad-exception-caught)
reinforce/experiments/hyperparameter_search.py:544:15: W0718: Catching too general exception Exception (broad-exception-caught)
reinforce/experiments/hyperparameter_search.py:572:15: W0718: Catching too general exception Exception (broad-exception-caught)
reinforce/experiments/hyperparameter_search.py:634:19: W0718: Catching too general exception Exception (broad-exception-caught)
reinforce/experiments/hyperparameter_search.py:625:27: W0718: Catching too general exception Exception (broad-exception-caught)
************* Module reinforce.agents.a2c.agent
reinforce/agents/a2c/agent.py:164:4: R0913: Too many arguments (6/5) (too-many-arguments)
reinforce/agents/a2c/agent.py:164:4: R0917: Too many positional arguments (6/5) (too-many-positional-arguments)
reinforce/agents/a2c/agent.py:164:4: R0914: Too many local variables (18/15) (too-many-locals)
************* Module reinforce.agents.a2c.a2c_model
reinforce/agents/a2c/a2c_model.py:14:0: W0223: Method '_restore_from_tensors' is abstract in class 'Trackable' but is not overridden in child class 'A2CModel' (abstract-method)
reinforce/agents/a2c/a2c_model.py:14:0: W0223: Method '_serialize_to_tensors' is abstract in class 'Trackable' but is not overridden in child class 'A2CModel' (abstract-method)
reinforce/agents/a2c/a2c_model.py:14:0: W0223: Method 'add_metric' is abstract in class 'Layer' but is not overridden in child class 'A2CModel' (abstract-method)
reinforce/agents/a2c/a2c_model.py:14:0: R0901: Too many ancestors (18/7) (too-many-ancestors)
reinforce/agents/a2c/a2c_model.py:79:4: W0221: Number of parameters was 3 in 'Model.call' and is now 4 in overriding 'A2CModel.call' method (arguments-differ)
reinforce/agents/a2c/a2c_model.py:79:4: W0221: Variadics removed in overriding 'A2CModel.call' method (arguments-differ)
************* Module reinforce.utils.aim_logger
reinforce/utils/aim_logger.py:103:15: W0718: Catching too general exception Exception (broad-exception-caught)
reinforce/utils/aim_logger.py:100:27: W0718: Catching too general exception Exception (broad-exception-caught)
reinforce/utils/aim_logger.py:142:15: W0718: Catching too general exception Exception (broad-exception-caught)
reinforce/utils/aim_logger.py:193:4: R0913: Too many arguments (6/5) (too-many-arguments)
reinforce/utils/aim_logger.py:296:4: R0913: Too many arguments (7/5) (too-many-arguments)
reinforce/utils/aim_logger.py:335:15: W0718: Catching too general exception Exception (broad-exception-caught)
reinforce/utils/aim_logger.py:344:4: R0913: Too many arguments (6/5) (too-many-arguments)
reinforce/utils/aim_logger.py:375:15: W0718: Catching too general exception Exception (broad-exception-caught)
reinforce/utils/aim_logger.py:395:19: W0718: Catching too general exception Exception (broad-exception-caught)
************* Module reinforce.trainers.episode_trainer
reinforce/trainers/episode_trainer.py:25:0: R0902: Too many instance attributes (12/7) (too-many-instance-attributes)
reinforce/trainers/episode_trainer.py:33:4: R0913: Too many arguments (6/5) (too-many-arguments)
reinforce/trainers/episode_trainer.py:102:4: R0914: Too many local variables (27/15) (too-many-locals)
reinforce/trainers/episode_trainer.py:142:27: W0718: Catching too general exception Exception (broad-exception-caught)
reinforce/trainers/episode_trainer.py:232:19: W0718: Catching too general exception Exception (broad-exception-caught)
reinforce/trainers/episode_trainer.py:240:4: R0913: Too many arguments (7/5) (too-many-arguments)
reinforce/trainers/episode_trainer.py:240:4: R0917: Too many positional arguments (7/5) (too-many-positional-arguments)
reinforce/trainers/episode_trainer.py:240:4: R0914: Too many local variables (17/15) (too-many-locals)
reinforce/trainers/episode_trainer.py:286:23: W0718: Catching too general exception Exception (broad-exception-caught)
reinforce/trainers/episode_trainer.py:353:23: W0718: Catching too general exception Exception (broad-exception-caught)
reinforce/trainers/episode_trainer.py:487:8: W1203: Use lazy % formatting in logging functions (logging-fstring-interpolation)

------------------------------------------------------------------
Your code has been rated at 9.65/10 (previous run: 9.24/10, +0.42)